const Database = require('better-sqlite3')
const db = new Database('dev.db')
const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all()
console.log('Tables:', JSON.stringify(tables.map(t => t.name)))
const plans = db.prepare("SELECT COUNT(*) as c FROM Plan").all()
console.log('Plan count:', plans[0].c)
const orders = db.prepare("SELECT COUNT(*) as c FROM `Order`").all()
console.log('Order count:', orders[0].c)
db.close()
